name: Docker Builds
on:
  workflow_dispatch:
  push:
    branches:
      - 'multi-arch'
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          # PHP 8
          - image: eksponent/php8
            context: php8
            dockerfile: Dockerfile-8-0-fpm
            tag: 8-0-fpm
          - image: eksponent/php8
            context: php8
            dockerfile: Dockerfile-8-1-fpm
            tag: 8-1-fpm

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.context }}
          file: ./${{ matrix.context }}/${{ matrix.dockerfile }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: eksponent/${{ matrix.image }}:${{ matrix.tag }}







